icmp_error: don't crash when msrc is NULL (debug builds only).
git-svn-id: http://www.virtualbox.org/svn/vbox@21996 cfe28804-0f27-0410-a406-dd0f0b0b656f